# Generated by Django 2.1 on 2019-04-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'verbose_name': 'Replay', 'verbose_name_plural': 'Replies'},
        ),
    ]
