# Generated by Django 2.1.7 on 2019-06-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserNotification', '0002_auto_20190610_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
    ]
