# Generated by Django 2.1.7 on 2019-06-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_deviceid'),
        ('UserNotification', '0003_auto_20190610_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='notifyuser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_notifyuser', to='user.User'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
