# Generated by Django 2.1.7 on 2019-03-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0001_initial'),
        ('review', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.NullBooleanField()),
                ('Type', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ProductReviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
                ('ScanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.Scan')),
            ],
            options={
                'verbose_name': 'Admin notifcaton ',
                'verbose_name_plural': 'Admin notifcatons',
            },
        ),
    ]
