# Generated by Django 2.1.7 on 2019-06-11 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminNotification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationadmin',
            name='ProductReviewID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
        migrations.AlterField(
            model_name='notificationadmin',
            name='ScanId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.Scan'),
        ),
    ]
