# Generated by Django 2.1.7 on 2019-03-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('UserName', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('IP', models.GenericIPAddressField()),
                ('Status', models.NullBooleanField()),
                ('ImageURL', models.URLField(blank=True, null=True)),
                ('WarningScore', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('BlockedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Admin')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
