# Generated by Django 2.1.7 on 2019-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190316_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='IP',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
