# Generated by Django 2.1.7 on 2019-06-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FCMToken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
