# Generated by Django 2.1.7 on 2019-05-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
